# Site settings
author: Christopher Beltran
title: From Madness To Mastery
header-img: img/home-bg.png
email: christod.beltran@gmail.com
copyright_name: Christopher Beltran
description: > # this means to ignore newlines until "baseurl:"
  One Commit At A Time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ChristopherBeltran

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
